config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  
  
  root to: 'pages#home'
  get 'market', to: 'pages#market'
  get 'quark', to: 'products#quark_order'
  get 'lepton', to: 'products#lepton_order'
  get 'proton', to: 'products#proton_order'
  
  
  get 'riddle', to: 'pages#riddle'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  validates :name, :presence => true
  validates :banner_image_url, :presence => true
  validates :title, :presence => true,
    :length => { :minimum => 5 }
  validates :content, :presence => true,
    :length => { :minimum => 5 }
    
  has_many :comments, :dependent => :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  
  
  private
    def contact_params
       params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def riddle
  end
  def market
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag].present?
      @posts = Post.all.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        flash[:success] =  "Post was successfully created."
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        flash[:danger] = @post.errors.full_messages.join(", ")
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post }
        flash[:success] =  "Post was successfully updated."
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        flash[:danger] = @post.errors.full_messages.join(", ")
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :banner_image_url, :tag_list)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
  def new
  end
    
  def orders
    @quark_order = Order.find(1)
    @lepton_order = Order.find(2)
    @proton_order = Order.find(3)
  end
  
  def lepton_order
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <% if user_signed_in? %>
    <%= link_to 'Delete', [comment.post, comment],
                 method: :delete,
                 class: "btn btn-danger",
                 data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p><br>
    <%= f.text_area :body, class: 'form-control', placeholder: "Enter your comment here..." %>
  </p>
  <p>
    <%= f.text_field :commenter, class: 'form', placeholder: "Name" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/contacts/new.html.erb
<div class="container">
    <h1 class="text-center">Contact Us</h1>
    <div class="">
      <%= form_for @contact do |f| %>
        <div class="w3-row">
          <div class="w3-col" style="width: 50%">
          <%= f.text_field :name, class: 'contact-text-field-name', placeholder: "Name" %>
          </div>
          <div class="w3-col" style="width: 50%">
          <%= f.text_field :email, class: 'contact-text-field-email', placeholder: "Email" %>
          </div>
          
        </div>
        <div class="form-group">
          <%= f.text_area :comments, class: 'contact-text-area', placeholder: "Message" %>
        </div>
        <%= f.submit 'Submit', class: 'invert-button' %>
      <% end %>
    </div>
    <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= if content_for?(:title) then yield(:title) + ' | ' end %>
      ApexVerse
    </title>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-6906335457793789",
        enable_page_level_ads: true
      });
    </script>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Cinzel|Dancing+Script|Open+Sans|Questrial|Russo+One|Lato|Montserrat|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <script src="https://cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Nav Bar-->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <div class="row">
              <%= image_tag("Logo .png", :alt => "Logo", size: "50x50", :id => "nav_logo") %>
              &nbsp;ApexVerse
            </div>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= 'active' if current_page?(posts_path) %>"><%= link_to "Blog", posts_path %></li>
            <li class="<%= 'active' if current_page?(market_path) %>"><%= link_to "MarketSpace", market_path %></li>
            <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
            <li class="<%= 'active' if current_page?(new_contact_path) %>"><%= link_to "Contact Us", new_contact_path %></li>
            <% if user_signed_in? %><li class="<%= 'active' if current_page?(new_post_path) %>"><%= link_to 'New Post', new_post_path %></li><% end %>
            <% if user_signed_in? %><li class="<%= 'active' if current_page?(destroy_user_session_path) %>"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li><% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
      
    
    <!--Dynamic Flash Message-->
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <!--Main Content-->
    <%= yield %>
    
    
     <!--Footer -->
    <footer class = "w3-light-grey">
        <div class="container text-center">
            <ul class="list-inline">
              <li>
                <a href="https://twitter.com/ApexVerse" target= "_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.facebook.com/ApexVerse-1664390790528809/" target= "_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                  <a href="https://www.instagram.com/ApexVerse/" target=_blank>
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
              </li>
            <p class="copyright text-muted text-align:center">Copyright <%= link_to "\u00A9", new_user_session_path %> ApexVerse 2017</p>  
          </ul>
        </div>
    </footer>
    
  </body>
</html>

app/views/order/order.html.erb
<%= form_for(resource, as: resource_name, url: order_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month" } %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year" } %>
  </div>
  <div class="actions form-group">
    <%= f.submit "Sign up", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/pages/about.html.erb
<div class="container text-center">
    <meta name="description" content="We are ApexVerse. Our company focuses on the newest in all social media
    and technology. We wish to connect people worldwide and to guide them to think
    ahead and move forward."
    
    <h1>About Page</h1>
    
    <p>We are ApexVerse. Our company focuses on the newest in all social media
    and technology. We wish to connect people worldwide and to guide them to think
    ahead and move forward.</p>
    
</div>

app/views/pages/home.html.erb
<header>
  <div class="container">
    <meta name="description" content="Where dreams become reality">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-text">
          <span class="name">ApexVerse</span>
            <hr class="star-light">
          <span class="skills">Where dreams become reality.</span>
        </div>
      </div>
    </div>
  </div>

  <div id="home-section-black" class="w3-grayscale-max" style="width:100%; height:790px">
    
    
  </div>

  <div id="home-section-white" class="w3-grayscale-max" style="width:100%; height:790px">
   
    <%= image_tag("Logo .png", :alt => "Logo", :align => "middle", :id => "logo") %>
    
    <p>We are ApexVerse. Our company focuses on the newest in all social media 
    and technology. We wish to connect people worldwide and to guide them to 
    think ahead and move forward.</p>
    
  </div>

</header>

app/views/pages/market.html.erb
<!-- Pricing Section -->

<!--Affilate link carasoul-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://placehold.it/1200x400?text=IMAGE" alt="Image">
      <div class="carousel-caption">
        <h3>Sell $</h3>
        <p>Money Money.</p>
      </div>      
    </div>

    <div class="item">
      <img src="https://placehold.it/1200x400?text=Another Image Maybe" alt="Image">
      <div class="carousel-caption">
        <h3>More Sell $</h3>
        <p>Lorem ipsum...</p>
      </div>      
    </div>
  </div>

<!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!--Website-->
<div class="w3-container w3-padding-128 w3-center w3-light-grey" id="website-pricing">
  <h1>Website Pricing</h1>
  <p class="w3-large">Choose a pricing plan that fits your needs.</p>
  
  <div class="w3-row-padding" style="margin-top:64px">
  
    <div class="w3-third w3-section" id="website-quark">
      <ul class="w3-ul w3-white w3-hover-shadow">
        <li class="w3-black w3-xlarge w3-padding-32">Quark</li>
        <li class="w3-padding-16"><b>3-5 Page Custom Website</b></li>
        <li class="w3-padding-16">Mobile Responsive</li>
        <li class="w3-padding-16">Hosting Set-up</li>
        <li class="w3-padding-16">Domain name</li>
        <li class="w3-padding-16">100% Satisfaction Guaranteed</li>
        <li class="w3-padding-16"><b>Free</b> 6 Months Maintenance</li>
        <li class="w3-padding-16">
          <h2><strike>$599</strike><b> $249</b></h2>
        </li>
        <li class="w3-light-grey w3-padding-24">
          <%= link_to "Order Now", "#", class: 'w3-button w3-black w3-padding-large' %>
        </li>
      </ul>
    </div>
  
    <div class="w3-third w3-section" id= "website-lepton">
      <ul class="w3-ul w3-white w3-hover-shadow">
        <li class="w3-black w3-xlarge w3-padding-32">Lepton</li>
        <li class="w3-padding-16"><b>6-8 Page Custom Website</b></li>
        <li class="w3-padding-16">Mobile Responsive</li>
        <li class="w3-padding-16">Google Analytic Integration</li>
        <li class="w3-padding-16">Hosting Set-up</li>
        <li class="w3-padding-16">Domain name</li>
        <li class="w3-padding-16">Marketing Consulting </li>
        <li class="w3-padding-16">100% Satisfaction Guaranteed</li>
        <li class="w3-padding-16"><b>Free</b> 6 month Maintenance</li>
        <li class="w3-padding-16">
          <h2 ><strike>$999</strike><b> $499 </b></h2>
        </li>
        <li class="w3-light-grey w3-padding-32">
         <%= link_to "Order Now", lepton_path(orders: @lepton_order),class: 'w3-button w3-black w3-padding-large' %>
        </li>
      </ul>
    </div>
    
    <div class="w3-third w3-section" id= "website-proton">
      <ul class="w3-ul w3-white w3-hover-shadow">
        <li class="w3-red w3-xlarge w3-padding-32">Proton</li>
        <li class="w3-padding-16"><b>10 Page Custom Website</b></li>
        <li class="w3-padding-16">Mobile Responsive</li>
        <li class="w3-padding-16">Google Analytic Integration</li>
        <li class="w3-padding-16">Ad Revenue Consulting</li>
        <li class="w3-padding-16">Hosting Set-up</li>
        <li class="w3-padding-16">Domain name</li>
        <li class="w3-padding-16">Marketing Consulting </li>
        <li class="w3-padding-16">100% Satisfaction Guaranteed</li>
        <li class="w3-padding-16"><b>Free</b> 1 year Maintenance</li>
        <li class="w3-padding-16">
          <h2 ><strike>$1499</strike><b> $999 </b></h2>
        </li>
        <li class="w3-light-grey w3-padding-24">
          <%= link_to "Order Now", proton_path(orders: @proton_order), class: 'w3-button w3-black w3-padding-large' %>
        </li>
      </ul>
    </div>
    
  </div>
</div>

<!-- Container (Services Section) -->
<div class="container-fluid" id="market_button">
  <div class="text-center" id="button_title">
    <h2 >SERVICES</h2>
  </div><br>
  
    <div class="container">    
      <div class="row">
        <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Aswin Mobile Plan</div>
            <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
            <div class="panel-footer">Buy 50 mobiles and get an Aswin Free</div>
          </div>
        </div>
         <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Aswin Mobile Plan</div>
            <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
            <div class="panel-footer">Buy 50 mobiles and get an Aswin Free</div>
          </div>
        </div>
         <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Aswin Mobile Plan</div>
            <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
            <div class="panel-footer">Buy 50 mobiles and get an Aswin Free</div>
          </div>
        </div>
         <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Aswin Mobile Plan</div>
            <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
            <div class="panel-footer">Buy 50 mobiles and get an Aswin Free</div>
          </div>
        </div>
         <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Aswin Mobile Plan</div>
            <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
            <div class="panel-footer">Buy 50 mobiles and get an Aswin Free</div>
          </div>
        </div>
         <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Aswin Mobile Plan</div>
            <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
            <div class="panel-footer">Buy 50 mobiles and get an Aswin Free</div>
          </div>
        </div>
      </div>
    </div><br>
</div>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>

  <div class="row">
    <div class="col-md-3">
      <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name , class: 'form-control' %>
      </div>
    
      <div class="field form-group">
        <%= f.label :title %>
        <%= f.text_field :title , class: 'form-control' %>
      </div>
    
      <div class="field form-group">
        <%= f.label :banner_image_url %>
        <%= f.text_field :banner_image_url , class: 'form-control' %>
      </div>
      
      <div class="field form-group">
        <%= f.label 'Tags' %>
        <%= f.text_field :tag_list , class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="field form-group">
        <%= f.label :content %>
        <%= f.text_area :content , class: 'form-control tinymce' %>
      </div>
    </div>
  </div>

  <div class="actions form-group">
    <%= f.submit "Save Post", :class => 'btn btn-primary'%>
    <%= link_to 'Back', posts_path , :class => 'btn btn-default'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Post</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="w3-content" style="max-width:1400px">
  
  <!-- Grid -->
  <div class="w3-row">
  
  <!-- Blog entries -->
  <div class="w3-col l8 s12">
    <!-- Blog entry -->
    <% @posts.each do |post| %>
    <div class="w3-card-4 w3-margin w3-white">
      <img src="<%= post.banner_image_url %>" alt="" style="width:100%" >
      <div class="w3-container w3-padding-8">
        <h1 id="post-title"><b><%= post.title %></b></h1>
        <h5 id="post-info"><%= post.name %> , <span class="w3-opacity"><%= post.created_at.strftime("%B %d %Y") %></span></h5>
      </div>
  
      <div class="w3-container">
        <p id="post-truncated"><%=raw post.content.truncate(323) %></p>
        <div class="w3-row">
          <div class="w3-col m8 s12">
            <%= button_to "READ MORE", post, class: 'invert-button', :method => "get" %>
          </div>
          <div class="w3-col m4 w3-hide-small">
            <p class="w3-right"><b>Comments </b> <span class="w3-tag"><%= post.comments.size %></span></p>
          </div>
        </div>
      </div>
      <br>
    </div>
    <% end %>
  <!-- END BLOG ENTRIES -->
  </div>
  
  <!-- Introduction menu -->
  <div class="w3-col l4">
    
    <!-- Most Popular Posts -->
    <div class="w3-card-2 w3-margin">
      <div class="w3-container w3-padding">
        <h4>Popular Posts</h4>
      </div>
      <ul class="w3-ul w3-hoverable w3-white">
        <% @posts.first(5).shuffle.each do |post| %>
        <li class="w3-padding-16">
          <span class="w3-large"><%= link_to post.title, post%></span><br>
          <span><%= post.created_at.strftime("%B %d %Y") %></span>
        </li>
        <% end %>
      </ul>
    </div>
     
   
    <!-- Labels / tags -->
    <div class="w3-card-2 w3-margin">
      <div class="w3-container w3-padding">
        <h4>Tags</h4>
      </div>
      <div class="w3-container w3-white">
        <p>
          <% ActsAsTaggableOn::Tag.all.each do |tag| %>
            <span class="w3-tag w3-light-grey w3-small w3-margin-bottom"><%= link_to tag.name, posts_path(tag: tag.name) %></span>
          <% end %>
        </p>
      </div>
    </div>
    
  <!-- END Introduction Menu -->
  </div>
  
  <!-- END GRID -->
  </div><br>
  
  
  
  
  
</div>

app/views/posts/show.html.erb
<div class="container text-center-left" id= "post_container">
  <meta name="description" content="<%= h truncate(@post.content, :length => 255) %>">
  <div class="intro-header")>
      <div class="container">
        <div class="post-heading">
          <h1 id="post_title"><%= @post.title %></h1>
            <span class="meta" id="post_info"><p id="post_name"><%= @post.name %></p><%= @post.created_at.strftime("%B, %d, %Y") %></span>
          <p>Tags: <%= raw @post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %></p>
        </div>
      </div>
  </div>
  <br>
  <div> 
    <%= social_share_button_tag(@post.title) %>
  </div>
  <br>
  <article>
    <div class="container">
      <p id="post_content"><%= @post.content.html_safe %></p>
    </div>
  </article>
  
  <%= link_to 'Back', posts_path , :class => 'btn btn-default'%>
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-warning' %>
    <%= link_to 'Delete', post_path(@post), method: :delete, :class => 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
  <% end %>
  
  
  <div class= "well" id="post_comments">
    <h2>Comments</h2>
    <%= render @post.comments %>
  </div>  
    
    <h2>Add a comment:</h2>
    <%= render "comments/form" %>
</div>

app/views/products/lepton_order.html.erb
<%= form_for :orders, url: lepton_path do |f| %>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.email_field :name, autofocus: true, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month" } %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year" } %>
  </div>
  <div class="actions form-group">
    <%= f.submit "Sign up", class: 'btn btn-success' %>
  </div>
<% end %>